RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes
OLED_ENABLE = yes
VIA_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = no
COMBO_ENABLE = yes
# SRC += features/tap_flow.c
SRC += features/achordion.c
OS_DETECTION_ENABLE = yes
